In [1]:
import pandas as pd 
import numpy as np
from sklearn.decomposition import PCA

In [3]:
df = pd.read_csv('Ratings.csv')
df.head()

B1  B2  B3  B4  B5
0   1   0   4   0   3
1   2   3   4   3   2
2   3   3   2   4   2
3   4   4   3   5   4
4   5   1   4   2   2

In [5]:
pca = PCA(svd_solver='randomized', random_state=42)

In [7]:
pca.fit(df)

PCA(copy=True, iterated_power='auto', n_components=None, random_state=42,
  svd_solver='randomized', tol=0.0, whiten=False)

In [8]:
pca.components_

array([[-0.31118649, -0.48101502,  0.35622281, -0.69199674, -0.25696953],
       [ 0.90672615, -0.31113879,  0.25507174, -0.09225738,  0.08641369],
       [-0.12857449, -0.38163517, -0.34923551, -0.16484744,  0.82986931],
       [ 0.1452065 , -0.34290409, -0.79235694, -0.05662208, -0.47989194],
       [-0.20831306, -0.63920934,  0.24134777,  0.69444104, -0.08671783]])

Once you perform PCA on the given dataset and project the data, what is the approximate variance explained by the first principal component?

In [9]:
pca.explained_variance_ratio_

array([6.51886873e-01, 1.52836342e-01, 1.30717403e-01, 6.43810220e-02,
       1.78359842e-04])

### Practice Questions

In [2]:
ratings_df = pd.read_csv('MyFoodRatings.csv')

In [3]:
ratings_df.head()

Name  Chicken  Mutton  Paneer  ChowMein  SpringRolls  Momo  Sushi  Ramen  \
0    A        5       5       5         0            0     0      0      0   
1    B        4       4       4         0            0     0      0      0   
2    C        3       3       3         0            0     0      0      0   
3    D        2       2       2         0            0     0      0      0   
4    E        0       0       0         2            2     2      0      0   

   Tempura  
0        0  
1        0  
2        0  
3        0  
4        0

In [18]:
ratings_df.shape

(12, 10)

In [7]:
ratings_minus_name_df = ratings_df.drop(columns='Name')

In [19]:
#Let'se use the SVD function from np.linalg library
U, s, VT = np.linalg.svd(ratings_minus_name_df, full_matrices=True)

In [20]:
U.shape

(12, 12)

In [21]:
VT.shape

(9, 9)

In [24]:
s

array([1.27279221e+01, 1.05770379e+01, 8.84826058e+00, 1.24205263e+00,
       1.06125858e+00, 4.06927550e-01, 3.87210908e-16, 3.62597321e-16,
       0.00000000e+00])

In [25]:
np.diag(s[:3])

array([[12.72792206,  0.        ,  0.        ],
       [ 0.        , 10.57703788,  0.        ],
       [ 0.        ,  0.        ,  8.84826058]])

In [31]:
pd.DataFrame(data=U)

0             1             2             3             4   \
0  -0.680414  3.021644e-17 -1.541699e-17 -8.601059e-17  9.064933e-17   
1  -0.544331  9.787916e-18 -4.993977e-18 -2.786114e-17  2.936375e-17   
2  -0.408248  7.340937e-18 -3.745483e-18 -2.089585e-17  2.202281e-17   
3  -0.272166 -1.061283e-16  5.414866e-17  3.020925e-16 -3.183850e-16   
4   0.000000 -3.262170e-01 -7.666822e-17 -4.277280e-16 -2.899287e-01   
5   0.000000 -1.631085e-01  5.081642e-17  4.003677e-16 -1.449643e-01   
6   0.000000 -6.643101e-01  6.162976e-33  4.930381e-32  7.474571e-01   
7   0.000000 -6.524340e-01  2.563000e-17  1.137721e-16 -5.798574e-01   
8   0.000000  0.000000e+00 -5.410479e-01 -8.368126e-01  0.000000e+00   
9   0.000000  0.000000e+00 -1.936803e-01  1.621542e-01  0.000000e+00   
10  0.000000  0.000000e+00 -7.209069e-01  4.102129e-01  0.000000e+00   
11  0.000000  0.000000e+00 -3.873606e-01  3.243085e-01  0.000000e+00   

              5             6         7         8             9   \
0  -1.760783e-16 -2.266545e-01 -0.408248 -0.544331 -2.653932e-03   
1  -5.703648e-17 -7.341946e-02 -0.132243  0.823677 -8.596798e-04   
2  -4.277736e-17 -5.506460e-02  0.900818 -0.132243 -6.447599e-04   
3   6.184347e-16  7.960720e-01 -0.066121 -0.088162  9.321331e-03   
4  -8.756318e-16  4.980948e-01  0.000000  0.000000 -1.319792e-02   
5   4.635115e-16 -5.859939e-02  0.000000  0.000000  4.350770e-01   
6   9.860761e-32  3.330669e-16  0.000000  0.000000 -3.469447e-18   
7   3.219380e-16 -2.343976e-01  0.000000  0.000000 -1.021703e-01   
8   8.373615e-02  0.000000e+00  0.000000  0.000000  8.326673e-17   
9   3.690446e-01  0.000000e+00  0.000000  0.000000  8.000000e-01   
10 -5.585862e-01  0.000000e+00  0.000000  0.000000  2.775558e-17   
11  7.380893e-01  0.000000e+00  0.000000  0.000000 -4.000000e-01   

              10            11  
0  -1.505543e-01 -5.307865e-03  
1  -4.876857e-02 -1.719360e-03  
2  -3.657643e-02 -1.289520e-03  
3   5.287876e-01  1.864266e-02  
4  -7.487018e-01 -2.639585e-02  
5   4.987230e-02  8.701539e-01  
6   5.551115e-17 -6.938894e-18  
7   3.618828e-01 -2.043406e-01  
8   4.440892e-16  1.665335e-16  
9  -5.273559e-16 -4.000000e-01  
10  3.330669e-16  5.551115e-17  
11 -1.054712e-15  2.000000e-01

In [32]:
pd.DataFrame(VT)

0         1         2         3         4         5         6  \
0 -0.577350 -0.577350 -0.577350 -0.000000 -0.000000 -0.000000 -0.000000   
1  0.000000  0.000000  0.000000 -0.637875 -0.512261 -0.575068  0.000000   
2  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000 -0.476163   
3  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.296110   
4 -0.000000 -0.000000 -0.000000  0.653030 -0.755593 -0.051282 -0.000000   
5 -0.000000 -0.000000 -0.000000 -0.000000 -0.000000 -0.000000  0.828002   
6  0.000000  0.000000  0.000000 -0.408248 -0.408248  0.816497  0.000000   
7 -0.816497  0.408248  0.408248 -0.000000 -0.000000 -0.000000 -0.000000   
8  0.000000 -0.707107  0.707107  0.000000  0.000000  0.000000  0.000000   

          7         8  
0  0.000000  0.000000  
1  0.000000  0.000000  
2 -0.557638 -0.679933  
3  0.626381 -0.721087  
4  0.000000  0.000000  
5 -0.544690 -0.133137  
6  0.000000  0.000000  
7  0.000000  0.000000  
8  0.000000  0.000000

In [34]:
ratings2_df = pd.read_csv('FoodRatings_all_same_5.csv')

In [35]:
ratings2_df.head()

Name  Chicken  Mutton  Paneer  ChowMein  SpringRolls  Momo  Sushi  Ramen  \
0    A        5       5       5         0            0     0      0      0   
1    B        5       5       5         0            0     0      0      0   
2    C        5       5       5         0            0     0      0      0   
3    D        5       5       5         0            0     0      0      0   
4    E        0       0       0         5            5     5      0      0   

   Tempura  
0        0  
1        0  
2        0  
3        0  
4        0

In [36]:
ratings2_without_name_df = ratings2_df.drop(columns='Name')

In [37]:
U2, s2, VT2 = np.linalg.svd(ratings2_without_name_df, full_matrices=True) 

In [39]:
pd.DataFrame(U2)

0    1    2         3         4         5         6             7   \
0   0.0  0.0 -0.5  0.866025  0.000000  0.000000  0.000000 -4.163336e-17   
1   0.0  0.0 -0.5 -0.288675 -0.144338  0.288675  0.288675 -5.773503e-01   
2   0.0  0.0 -0.5 -0.288675 -0.052831  0.105662  0.105662  7.886751e-01   
3   0.0  0.0 -0.5 -0.288675  0.197169 -0.394338 -0.394338 -2.113249e-01   
4  -0.5  0.0  0.0  0.000000  0.125000 -0.250000 -0.250000  0.000000e+00   
5  -0.5  0.0  0.0  0.000000  0.125000 -0.250000  0.750000  0.000000e+00   
6  -0.5  0.0  0.0  0.000000 -0.375000 -0.250000 -0.250000  0.000000e+00   
7  -0.5  0.0  0.0  0.000000  0.125000  0.750000 -0.250000  0.000000e+00   
8   0.0 -0.5  0.0  0.000000  0.750000  0.000000  0.000000  0.000000e+00   
9   0.0 -0.5  0.0  0.000000 -0.250000  0.000000  0.000000  0.000000e+00   
10  0.0 -0.5  0.0  0.000000 -0.250000  0.000000  0.000000  0.000000e+00   
11  0.0 -0.5  0.0  0.000000 -0.250000  0.000000  0.000000  0.000000e+00   

          8         9         10        11  
0   0.000000  0.000000  0.000000  0.000000  
1   0.288675 -0.144338 -0.144338 -0.144338  
2   0.105662 -0.052831 -0.052831 -0.052831  
3  -0.394338  0.197169  0.197169  0.197169  
4   0.750000  0.125000  0.125000  0.125000  
5  -0.250000  0.125000  0.125000  0.125000  
6  -0.250000 -0.375000 -0.375000 -0.375000  
7  -0.250000  0.125000  0.125000  0.125000  
8   0.000000 -0.250000 -0.250000 -0.250000  
9   0.000000  0.750000 -0.250000 -0.250000  
10  0.000000 -0.250000  0.750000 -0.250000  
11  0.000000 -0.250000 -0.250000  0.750000

In [40]:
s2

array([1.73205081e+01, 1.73205081e+01, 1.73205081e+01, 2.51214793e-15,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00])

In [41]:
ratings3_df = pd.read_csv('FoodRatings_all_same_5_4_3.csv')

In [42]:
ratings3_without_name_df = ratings3_df.drop(columns='Name')

In [43]:
U3, s3, VT3 = np.linalg.svd(ratings3_without_name_df, full_matrices=True) 

In [44]:
s3

array([1.73205081e+01, 1.38564065e+01, 1.03923048e+01, 2.51214793e-15,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00])