In [7]:
import numpy as np
import pandas as pd

In [3]:
pd_list1 = pd.Series([6,7,8,9,2,3,4,5])
print(pd_list1)

0    6
1    7
2    8
3    9
4    2
5    3
6    4
7    5
dtype: int64


In [6]:
pd_list2 = pd.Series(pd_list1 ** 2) 
print (pd_list2)

In [8]:
tempfunc = lambda x : x ** 2
pd_list3 = pd_list1.apply(tempfunc) 
print (pd_list3)

0    36
1    49
2    64
3    81
4     4
5     9
6    16
7    25
dtype: int64


In [15]:
n = int(input())
#series_1 = pd.Series(np.arange(1,n+1)**2,index=np.arange(1,n+1))
series_1 = pd.Series(np.array(range(1,n+1))**2, index=range(1,n+1))
print(series_1)

4
1     1
2     4
3     9
4    16
dtype: int32


In [22]:
df = pd.read_csv('https://query.data.world/s/vBDCsoHCytUSLKkLvq851k2b8JOCkF')
#print (df.head())
df_2 = df.set_index('X', inplace=False)#Type your code here
print(df_2.head())

   Y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area
X                                                                  
7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0
7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0
7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0
8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0
8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0


In [8]:
gold = pd.DataFrame({'Country': ['USA', 'France', 'Russia'],
                         'Medals': [15, 13, 9]}
                    )
silver = pd.DataFrame({'Country': ['USA', 'Germany', 'Russia'],
                        'Medals': [29, 20, 16]}
                    )
bronze = pd.DataFrame({'Country': ['France', 'USA', 'UK'],
                        'Medals': [40, 28, 27]}
                    )

In [9]:
gold.set_index('Country', inplace=True)
silver.set_index('Country', inplace=True)
bronze.set_index('Country', inplace=True)

In [12]:
total = gold.add(silver, fill_value=0).add(bronze, fill_value=0)
total.sort_values(by='Medals', ascending=False)

Medals
Country        
USA        72.0
France     53.0
UK         27.0
Russia     25.0
Germany    20.0

In [18]:
df = pd.read_csv('https://query.data.world/s/vBDCsoHCytUSLKkLvq851k2b8JOCkF')
#Type your groupby command here
df_1 = df.groupby(['month','day'])
df_1 = df_1['rain','wind'].mean()#Type your code to find the mean of columns 'rain' and 'wind'
print(df_1.head(20))

               rain      wind
month day                    
apr   fri  0.000000  3.100000
      mon  0.000000  3.100000
      sat  0.000000  4.500000
      sun  0.000000  5.666667
      thu  0.000000  5.800000
      wed  0.000000  2.700000
aug   fri  0.066667  4.766667
      mon  0.000000  2.873333
      sat  0.000000  4.310345
      sun  0.025000  4.417500
      thu  0.000000  3.503846
      tue  0.300000  4.567857
      wed  0.000000  3.520000
dec   fri  0.000000  4.900000
      mon  0.000000  8.500000
      sun  0.000000  8.500000
      thu  0.000000  4.900000
      tue  0.000000  8.500000
      wed  0.000000  8.000000
feb   fri  0.000000  4.820000


In [6]:
df = pd.read_csv('https://query.data.world/s/vBDCsoHCytUSLKkLvq851k2b8JOCkF')
df_1 = df.pivot_table(values=['rain','wind'], index=['month','day'],aggfunc = 'mean')
print(df_1.head(20))

               rain      wind
month day                    
apr   fri  0.000000  3.100000
      mon  0.000000  3.100000
      sat  0.000000  4.500000
      sun  0.000000  5.666667
      thu  0.000000  5.800000
      wed  0.000000  2.700000
aug   fri  0.066667  4.766667
      mon  0.000000  2.873333
      sat  0.000000  4.310345
      sun  0.025000  4.417500
      thu  0.000000  3.503846
      tue  0.300000  4.567857
      wed  0.000000  3.520000
dec   fri  0.000000  4.900000
      mon  0.000000  8.500000
      sun  0.000000  8.500000
      thu  0.000000  4.900000
      tue  0.000000  8.500000
      wed  0.000000  8.000000
feb   fri  0.000000  4.820000


In [8]:
df = pd.read_csv('https://query.data.world/s/Hfu_PsEuD1Z_yJHmGaxWTxvkz7W_b0')

In [9]:
df

Ord_id  Prod_id   Ship_id    Cust_id       Sales  Discount  \
0     Ord_5446  Prod_16  SHP_7609  Cust_1818    136.8100      0.01   
1     Ord_5406  Prod_13  SHP_7549  Cust_1818     42.2700      0.01   
2     Ord_5446   Prod_4  SHP_7610  Cust_1818   4701.6900      0.00   
3     Ord_5456   Prod_6  SHP_7625  Cust_1818   2337.8900      0.09   
4     Ord_5485  Prod_17  SHP_7664  Cust_1818   4233.1500      0.08   
5     Ord_5446   Prod_6  SHP_7608  Cust_1818    164.0200      0.03   
6       Ord_31  Prod_12    SHP_41    Cust_26     14.7600      0.01   
7     Ord_4725   Prod_4  SHP_6593  Cust_1641   3410.1575      0.10   
8     Ord_4725  Prod_13  SHP_6593  Cust_1641    162.0000      0.01   
9     Ord_4725   Prod_6  SHP_6593  Cust_1641     57.2200      0.07   
10    Ord_4743   Prod_2  SHP_6615  Cust_1641   4072.0100      0.01   
11    Ord_1925   Prod_6  SHP_2637   Cust_708    465.9000      0.05   
12    Ord_2978  Prod_16  SHP_4112  Cust_1088    305.0500      0.04   
13    Ord_2207  Prod_11  SHP_3093   Cust_839   3364.2480      0.10   
14    Ord_2207  Prod_10  SHP_3006   Cust_839   1410.9300      0.08   
15    Ord_2280   Prod_5  SHP_3114   Cust_839    460.6900      0.06   
16    Ord_2282   Prod_9  SHP_3122   Cust_839    443.4600      0.06   
17    Ord_4471  Prod_15  SHP_6228  Cust_1521  13255.9300      0.02   
18    Ord_4427   Prod_6  SHP_6171  Cust_1521    283.1300      0.08   
19     Ord_996  Prod_13  SHP_1378   Cust_371     41.9700      0.05   
20     Ord_996  Prod_13  SHP_1378   Cust_371     57.1700      0.08   
21     Ord_996   Prod_6  SHP_1378   Cust_371     81.2500      0.01   
22     Ord_996   Prod_5  SHP_1377   Cust_371   3202.2500      0.09   
23     Ord_996   Prod_7  SHP_1378   Cust_371     35.6400      0.05   
24    Ord_2573   Prod_3  SHP_3525   Cust_931    197.6100      0.08   
25    Ord_2335  Prod_13  SHP_3204   Cust_931     38.2600      0.03   
26    Ord_2456   Prod_5  SHP_3367   Cust_931    109.5800      0.00   
27    Ord_2405   Prod_9  SHP_3300   Cust_931   1062.6900      0.01   
28    Ord_2573   Prod_4  SHP_3527   Cust_931   3594.7435      0.05   
29    Ord_2478  Prod_12  SHP_3395   Cust_931    139.9800      0.07   
...        ...      ...       ...        ...         ...       ...   
8369  Ord_3633   Prod_3  SHP_5031  Cust_1274   1169.2600      0.02   
8370  Ord_2696  Prod_13  SHP_3690  Cust_1006     62.7800      0.04   
8371  Ord_2624   Prod_4  SHP_3591  Cust_1006   4924.1350      0.07   
8372  Ord_2772   Prod_9  SHP_3806  Cust_1006     56.9000      0.03   
8373  Ord_2600  Prod_16  SHP_3560  Cust_1006    106.6400      0.10   
8374  Ord_2658   Prod_5  SHP_3637  Cust_1006   1082.6600      0.08   
8375  Ord_2772   Prod_3  SHP_3806  Cust_1006   1413.8200      0.10   
8376  Ord_2624   Prod_8  SHP_3590  Cust_1006   1211.0000      0.00   
8377  Ord_2722  Prod_12  SHP_3729  Cust_1006     34.0100      0.00   
8378  Ord_2706   Prod_2  SHP_3705  Cust_1006   1361.9100      0.05   
8379  Ord_2722   Prod_5  SHP_3730  Cust_1006   1008.9500      0.04   
8380  Ord_2772   Prod_6  SHP_3807  Cust_1006    308.9200      0.04   
8381  Ord_2696   Prod_4  SHP_3691  Cust_1006   2836.0505      0.01   
8382  Ord_2658   Prod_3  SHP_3636  Cust_1006    120.9800      0.00   
8383  Ord_2722   Prod_1  SHP_3731  Cust_1006   3508.3300      0.04   
8384  Ord_4620   Prod_3  SHP_6435  Cust_1577     59.6200      0.04   
8385  Ord_1833   Prod_3  SHP_2527   Cust_637    611.1600      0.04   
8386  Ord_2324   Prod_7  SHP_3189   Cust_851    121.8700      0.07   
8387  Ord_2220   Prod_3  SHP_3019   Cust_851     41.0600      0.04   
8388  Ord_4424   Prod_1  SHP_6165  Cust_1519    994.0400      0.03   
8389  Ord_4444  Prod_13  SHP_6192  Cust_1519    159.4100      0.00   
8390  Ord_5435  Prod_16  SHP_7594  Cust_1798         NaN       NaN   
8391  Ord_5435   Prod_4  SHP_7594  Cust_1798         NaN       NaN   
8392  Ord_5384   Prod_9  SHP_7519  Cust_1798         NaN       NaN   
8393  Ord_5348   Prod_8  SHP_7470  Cust_1798         NaN       NaN   
8394  Ord_5353   P

In [11]:
df.isnull().sum()

Ord_id                   0
Prod_id                  0
Ship_id                  0
Cust_id                  0
Sales                   20
Discount                55
Order_Quantity          55
Profit                  55
Shipping_Cost           55
Product_Base_Margin    109
dtype: int64

In [18]:
df = pd.read_csv('https://query.data.world/s/Hfu_PsEuD1Z_yJHmGaxWTxvkz7W_b0')
print('Original::',df.shape)
print(round(100*(df.isnull().sum(axis=1)/len(df.index)),2))
df = df[df.isnull().sum(axis=1) <= 5]
print('Modified::',df.shape)
print(round(100*(df.isnull().sum()/len(df.index)),2))

Original:: (8399, 10)
0       0.00
1       0.00
2       0.00
3       0.00
4       0.00
5       0.00
6       0.00
7       0.00
8       0.00
9       0.00
10      0.00
11      0.00
12      0.00
13      0.00
14      0.00
15      0.00
16      0.00
17      0.00
18      0.00
19      0.00
20      0.00
21      0.00
22      0.00
23      0.00
24      0.00
25      0.00
26      0.00
27      0.00
28      0.00
29      0.00
        ... 
8369    0.00
8370    0.00
8371    0.00
8372    0.00
8373    0.00
8374    0.00
8375    0.00
8376    0.00
8377    0.00
8378    0.00
8379    0.00
8380    0.00
8381    0.00
8382    0.00
8383    0.00
8384    0.00
8385    0.00
8386    0.00
8387    0.00
8388    0.01
8389    0.00
8390    0.07
8391    0.07
8392    0.07
8393    0.07
8394    0.07
8395    0.07
8396    0.07
8397    0.07
8398    0.07
Length: 8399, dtype: float64
Modified:: (8379, 10)
Ord_id                 0.00
Prod_id                0.00
Ship_id                0.00
Cust_id                0.00
Sales                 

In [31]:
df = pd.read_csv('https://query.data.world/s/Hfu_PsEuD1Z_yJHmGaxWTxvkz7W_b0')
mean1 = df['Product_Base_Margin'].mean()
print(mean1)
df.loc[np.isnan(df['Product_Base_Margin']),['Product_Base_Margin']]=mean1
print(round(100*(df.isnull().sum()/len(df.index)),2))

0.5124813027744285
Ord_id                 0.00
Prod_id                0.00
Ship_id                0.00
Cust_id                0.00
Sales                  0.24
Discount               0.65
Order_Quantity         0.65
Profit                 0.65
Shipping_Cost          0.65
Product_Base_Margin    0.00
dtype: float64


In [36]:
#index of100th element

arr1 = np.arange(1,133).reshape(11,12)
arr1

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12],
       [ 13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36],
       [ 37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48],
       [ 49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72],
       [ 73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84],
       [ 85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96],
       [ 97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108],
       [109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120],
       [121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132]])

In [68]:
#Given m and n, swap the mth and nth rows of the 2-D NumPy array given below.
# Given array
a = np.array([[4, 3, 1], [5, 7, 0], [9, 9, 3], [8, 2, 4]])

# Read the values of m and n
m = int(input())
n = int(input())
##temp = a[m,:].copy()
##a[m,:]=a[n,:]
##a[n,:]=temp


a[[m,n]] = a[[n,m]]
print(a)

0
2
[[4 3 1]
 [5 7 0]
 [9 9 3]
 [8 2 4]]
[[4 3 1]
 [9 9 3]]
[[9 9 3]
 [5 7 0]
 [4 3 1]
 [8 2 4]]


In [43]:
#Given a single integer n, create an (n x n) 2D array with 1 on the border and 0 on the inside. 
n = int(input())
arr = np.full((n,n),0)
arr[0,:]=1
arr[n-1,:]=1
arr[:,0]=1
arr[:,n-1]=1
print(arr)
    


7
[[1 1 1 1 1 1 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 1 1 1 1 1 1]]
